Split all classes into their own files. Prior comments still valid with additions to integrate with Optimatics code (see below).
In the process of adding pdata modification. Current error:
Traceback (most recent call last):
  File "C:\Users\nschiff2\.IntelliJIdea15\config\plugins\python\helpers\pydev\pydevd.py", line 2403, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\nschiff2\.IntelliJIdea15\config\plugins\python\helpers\pydev\pydevd.py", line 1794, in run
    launch(file, globals, locals)  # execute the script
  File "C:/Users/nschiff2/ISWS_MWRDGC_WSRR/InitHMS.py", line 612, in <module>
    readBasinFile(ws['basinin'], ws['basinout'], ws['pdatafile'], ws['dssfile'], ws['redevelopment'], ws['curvenumber'],
  File "C:/Users/nschiff2/ISWS_MWRDGC_WSRR/InitHMS.py", line 564, in readBasinFile
    shutil.copyfileobj(pdatasink, pdatabackup)
  File "C:\jython2.7.0\Lib\shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
IOError: BufferedWriter.readinto() not supported

To-do list:
--Button executes setParams, but program does not wait for user input.
--Need to add choices for watershed and subwatershed.
--Program exits after last line in __main__, but with exit code -1.
--write storage-outflow names to file, one per line
--write subbasin names, areas, and release rates to JSON file for input into Optimatics code